### ISSUE TITLE
futures::compat::*

### ISSUE THREAD

**Issue by mihai-dinculescu** [davidpdrsn/witter#1]
`futures::compat::*` is brought in by the `compat` feature.

`futures = { version = "0.3.5", features = ["compat"] }`

**Comment by davidpdrsn** [comment]
Yeah I realized that yesterday while poking around. Really should be mentioned in docs very clearly.

**Comment by davidpdrsn** [comment]
We fixed this as part of the last stream. Thanks for the tip!
