### ISSUE TITLE
CI build is broken

### ISSUE THREAD

**Issue by davidpdrsn** [davidpdrsn/witter#12]
https://travis-ci.org/github/davidpdrsn/witter/jobs/698262200#L1220

It seems the build server doesn't see the database while compiling which causes the sqlx macros to fail.

**Comment by amcsi** [comment]
@davidpdrsn the script line to load the sql file failed as per the output. The cause is that the .sql file has moved since when I first wrote .travis.yml

The fix should be here: #13

It should be green hopefully

**Comment by davidpdrsn** [comment]
Was indeed fixed in https://github.com/davidpdrsn/witter/pull/13
