### ISSUE TITLE
Is our implementation of CorsMiddleware still required?

### ISSUE THREAD

**Issue by hadichaudhri** [davidpdrsn/witter#14]
Initially, we implemented our own hotfixed version of the middleware because Error values did not get correct CORS headers applied to them. However, this was resolved at around by making our ErrorReponseToJson middleware run first. [You explain that this effectively makes the error path in our CorsMiddleware unreachable](https://youtu.be/668vvEzzMnI?t=10940). Does this mean that we can remove our implementation without recourse?

**Comment by davidpdrsn** [comment]
I think once we dive more into the frontend we should test make sure everything still works without `CorsMiddleware`. The tide issue I opened hasn't seen much attention lately https://github.com/http-rs/tide/issues/525

**Comment by sync** [comment]
you no longer need it

**Comment by sync** [comment]
also you can also just use:

```
    let cors = CorsMiddleware::new();
    server.middleware(cors);

```

and the default should do the right thing

**Comment by davidpdrsn** [comment]
Nope its not needed anymore 😊 I've removed it.
